export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND";
export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CLEAR_CURRENT_CUSTOMER = "CLEAR_CURRENT_CUSTOMER";
export const CLEAR_CURRENT_CUSTOMERS = "CLEAR_CURRENT_CUSTOMERS";
export const SET_CURRENT_CUSTOMER = "SET_CURRENT_CUSTOMER";

export const GET_DELIVERY = "GET_DELIVERY";
export const GET_DELIVERIES = "GET_DELIVERIES";
export const ADD_DELIVERY = "ADD_DELIVERY";
export const UPDATE_DELIVERY = "UPDATE_DELIVERY";
export const DELIVERY_NOT_FOUND = "DELIVERY_NOT_FOUND";
export const DELIVERY_LOADING = "DELIVERY_LOADING";
export const CLEAR_CURRENT_DELIVERY = "CLEAR_CURRENT_DELIVERY";
export const CLEAR_CURRENT_DELIVERIES = "CLEAR_CURRENT_DELIVERIES";
export const SET_CURRENT_DELIVERY = "SET_CURRENT_DELIVERY";
export const GET_ID = "GET_ID";
export const ADD_CONTACT = "ADD_CONTACT";

export const GET_FILE = "GET_FILE";
export const GET_FILES = "GET_FILES";
export const FILE_NOT_FOUND = "FILE_NOT_FOUND";
export const FILE_LOADING = "FILE_LOADING";
export const CLEAR_CURRENT_FILE = "CLEAR_CURRENT_FILE";
export const CLEAR_CURRENT_FILES = "CLEAR_CURRENT_FILES";

export const GET_CONTAINER = "GET_CONTAINER";
export const GET_CONTAINERS = "GET_CONTAINERS";
export const CONTAINER_NOT_FOUND = "CONTAINER_NOT_FOUND";
export const CONTAINER_LOADING = "CONTAINER_LOADING";
export const CLEAR_CURRENT_CONTAINER = "CLEAR_CURRENT_CONTAINER";
export const CLEAR_CURRENT_CONTAINERS = "CLEAR_CURRENT_CONTAINERS";
export const SET_CURRENT_CONTAINER = "SET_CURRENT_CONTAINER";
